# Generated by Django 4.1.4 on 2022-12-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookinstance_browser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='browser',
            new_name='borrower',
        ),
    ]
